import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const DynamicHeader = dynamic(() => import('./header'), {
        ssr: false,
    })

    const DynamicHome = dynamic(() => import('./home'), {
        ssr: false,
    })

    const DynamicEnvironment = dynamic(() => import('./environment'), {
        ssr: false,
    })

    const DynamicCompanies = dynamic(() => import('./companies'), {
        ssr: false,
    })
    const DynamicInstant = dynamic(() => import('./instant'), {
        ssr: false,
    })
    const DynamicQuotes = dynamic(() => import('./quotes'), {
        ssr: false,
    })
    const DynamicBeforefotter = dynamic(() => import('./beforefotter'), {
        ssr: false,
    })

    return (
        <>
            <Head>
                <title>StackBlitz_Clone</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://avatars.githubusercontent.com/u/28635252?s=200&v=4" />
            </Head>
            <DynamicHeader />
            <main >
                <DynamicHome />
                <DynamicEnvironment />
                <DynamicCompanies />
                <DynamicInstant />
                <DynamicQuotes />
                <DynamicBeforefotter />
            </main>
        </>
    )
}
