import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const DynamicHeader = dynamic(() => import('./header'), {
        ssr: false,
    })

    const DynamicHome = dynamic(() => import('./home'), {
        ssr: false,
    })

    const DynamicEnvironment = dynamic(() => import('./environment'), {
        ssr: false,
    })

    const DynamicCompanies = dynamic(() => import('./companies'), {
        ssr: false,
    })
    const DynamicInstant = dynamic(() => import('./instant'), {
        ssr: false,
    })
    const DynamicQuotes = dynamic(() => import('./quotes'), {
        ssr: false,
    })
    const DynamicBeforefotter = dynamic(() => import('./beforefotter'), {
        ssr: false,
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DynamicHeader />
            <main >
                <DynamicHome />
                <DynamicEnvironment />
                <DynamicCompanies />
                <DynamicInstant />
                <DynamicQuotes />
                <DynamicBeforefotter />
            </main>
        </>
    )
}
